services:
  backend:
    build:
      context: ../
      dockerfile: entrance-cockpit/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=192.68.0.50:9092
      - POSTGRES_SERVER=192.168.0.33:5432
    restart: unless-stopped








