version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"   # MQTT
    volumes:
      - ./mqtt-broker/mosquitto/config:/mosquitto/config
      - ./mqtt-broker/mosquitto/data:/mosquitto/data
      - ./mqtt-broker/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  bridge-messaging:
    build: ./bridge-messaging
    environment:
      - KAFKA_BOOTSTRAP=172.31.125.112:9092
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    depends_on:
      - mqtt
