#this is context properties
#Wed Dec 03 17:32:13 CET 2025
postgres_Schema=public
postgres_Password=enc\:routine.encryption.key.v1\:depAgnrM0hmvFzeVkkKgFz/M7+sZtPCCqHihnnVjPKAsuuAy
postgres_AdditionalParams=
postgres_Login=postgres
postgres_Server=localhost
postgres_Port=5432
postgres_Database=playersdata
