#just for tac
statistics=true
job=silvertogold
jobVersion=0.1
date=2025-12-03 222828633
contextName=Default
jobId=_MRtrUNA1EfCAWtx4brs-Zg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=LOCAL_PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=