services:
  iot-components:
    build: .
    command: sh -c "npx tsx Main.ts"
    environment:
      - MATCH_ID=${MATCH_ID:-1}
      - DURATION=${DURATION:-90}
      - ACTIONS=${ACTIONS:-3}
      - MQTT_BROKER=172.31.249.162:8883
      - API_BASE_URL=http://172.31.249.162