#this is context properties
#Thu Feb 26 00:08:34 CET 2026
mongo_server=172.31.249.162
mongo_collection_bronze=bronze
mongo_collection_silver=silver
mongo_database=playersdata
mongo_kpia=mongo_kpia
mongo_player_injuries=player_injuries
mongo_player_injuries_modifie=player_injuries_modifie
mongo_player_latest_market_value=player_latest_market_value
mongo_player_latest_market_value_modifie=player_latest_market_value_modifie
mongo_player_performances=player_performances
mongo_player_performances_modifie=player_performances_modifie
mongo_player_profiles=player_profiles
mongo_player_profiles_modifie=player_profiles_modifie
mongo_port=27017
mongo_team_details=team_details
mongo_team_details_modifie=team_details_modifie
mongo_transfer_history=transfer_history
mongo_transfer_history_modifie=mongo_transfer_history_modifie
postgres_database=playersdata
postgres_password=Ravus77\!
postgres_port=5432
postgres_schema=gold
postgres_server=192.168.0.33
postgres_table_bodytype=bodytype
postgres_table_players=players
postgres_user=admin
source=/home/usercm/data-pipeline/fifa_players.csv
source_player_injuries=/data/data_raw/player_injuries.csv
source_player_latest_market_value=/data/data_raw/player_latest_market_value.csv
source_player_performances=/data/data_raw/player_performances.csv
source_player_profiles=/data/data_raw/player_profiles.csv
source_team_details=/data/data_raw/team_details.csv
source_transfer_history=/data/data_raw/transfer_history.csv
