#just for tac
statistics=true
job=sourcetobronze
jobVersion=0.1
date=2025-12-04 173602597
contextName=Default
jobId=_2A1mMNEkEfCI_a0scet84w
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=LOCAL_PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=