FROM node:18 AS build
WORKDIR /app

ARG VITE_ENTRANCE_COCKPIT_SERVER
ENV VITE_ENTRANCE_COCKPIT_SERVER=${VITE_ENTRANCE_COCKPIT_SERVER}

COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]