#this is context properties
#Thu Dec 04 00:16:24 CET 2025
postgres_Schema=public
postgres_Password=enc\:routine.encryption.key.v1\:hWGv3msFvn34ilLfaYY6BdKNOgZvOlxqTwkRBfoy8k5nPd9u
postgres_AdditionalParams=
postgres_Login=postgres
postgres_Server=localhost
postgres_Port=5432
postgres_Database=playersdata
