#this is context properties
#Thu Dec 04 18:35:27 CET 2025
postgres_Schema=public
postgres_Password=enc\:routine.encryption.key.v1\:4ydXqHzOcU3imo+9oBAuI6auOIZdigtN5Bm4SX7fyTvVvJp/
postgres_AdditionalParams=
postgres_Login=postgres
postgres_Server=localhost
postgres_Port=5432
postgres_Database=playersdata
postgres_table_name=name
postgres_table_nationality=nationality
mongo_collection_bronze=bronze
mongo_collection_silver=silver
mongo_database=playersdata
mongo_port=27017
mongo_server=192.168.0.31
postgres_table_bodytype=bodytype
postgres_table_players=players
postgres_user=admin
source=/home/usercm/data-pipeline/fifa_players.csv
