#just for tac
statistics=true
job=bronzetosilver
jobVersion=0.1
date=2026-02-24 165915916
contextName=Default
jobId=_ts9GwA8lEfGG5so2ikSyTg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=LOCAL_PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=