spring.application.name=player-performance
server.port=8081

spring.kafka.streams.properties.default.application.id=player-performance
spring.kafka.streams.replication-factor=1


spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


spring.kafka.streams.properties.num.stream.threads=1
spring.kafka.streams.properties.commit.interval.ms=1000
spring.kafka.streams.properties.cache.max.bytes.buffering=0
spring.kafka.streams.properties.state.dir=/tmp/kafka-streams
spring.kafka.streams.properties.processing.guarantee=at_least_once

spring.kafka.streams.properties.spring.json.trusted.packages=club.manager.player_performance.model,tools.jackson.databind,tools.jackson.databind.node,java.util,java.lang
