name: Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Set IMAGE_TAG
      #  run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Create Docker secrets
        run: |
          echo "${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}" | docker secret create kc_admin_password - || true
          echo "${{ secrets.KEYCLOAK_PASSWORD_DB}}" | docker secret create kc_db_password - || true

      - name: Login Docker on all nodes
        run: |
          ssh usercm@192.168.0.10 docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          ssh usercm@192.168.0.80 docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          ssh usercm@192.168.0.90 docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          ssh usercm@192.168.0.32 docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          ssh usercm@192.168.0.65 docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          ssh usercm@192.168.0.60 docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          ssh usercm@192.168.0.34 docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./static-server
          push: true
          build-args: |
            VITE_ENTRANCE_COCKPIT_SERVER=https://172.31.249.162
          #clubmanagersirius/static-server-backend:${{ env.IMAGE_TAG }}
          tags: |
            clubmanagersirius/static-server-backend:latest
      - name: Build & Push entrance-cockpit
        uses: docker/build-push-action@v4
        with:
          context: .
          file: entrance-cockpit/Dockerfile
          push: true
          #clubmanagersirius/entrance-cockpit-backend:${{ env.IMAGE_TAG }}
          tags: |
            clubmanagersirius/entrance-cockpit-backend:latest

      - name: Build & Push bridge-messaging
        uses: docker/build-push-action@v4
        with:
          context: ./bridge-messaging
          push: true
          #clubmanagersirius/bridge-messaging:${{ env.IMAGE_TAG }}
          tags: |
            clubmanagersirius/bridge-messaging:latest

      - name: Build & Push data-pipeline
        uses: docker/build-push-action@v4
        with:
          context: ./data-pipeline
          push: true
          #clubmanagersirius/data-pipeline:${{ env.IMAGE_TAG }}
          tags: | 
            clubmanagersirius/data-pipeline:latest

  deploy-dev:
    needs: build-and-push
    #if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Set IMAGE_TAG
      #  run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy Stack Dev
        #run: IMAGE_TAG=${{ env.IMAGE_TAG }} docker stack deploy -c docker-stack-dev.yml club_manager_dev --with-registry-auth
        env:
          KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
          KEYCLOAK_PASSWORD_DB: ${{ secrets.KEYCLOAK_PASSWORD_DB }}
        run: docker stack deploy -c docker-stack-dev.yml club_manager_dev --with-registry-auth

  deploy-prod:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     # - name: Set IMAGE_TAG
     #   run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy Stack Prod
      #run: IMAGE_TAG=${{ env.IMAGE_TAG }} docker stack deploy -c docker-stack-prod.yml club_manager_prod --with-registry-auth
        run: docker stack deploy -c docker-stack-prod.yml club_manager_prod --with-registry-auth