name: Update Nginx Config

on:
  workflow_dispatch:

jobs:
  update-nginx:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update nginx config
        run: |
          docker config create nginx_conf_new ./reverse-proxy/nginx.conf
          docker config create nginx_snippets_oauth2_new ./reverse-proxy/snippets/oauth2_headers.conf
          docker service update \
            --config-rm nginx_conf \
            --config-add source=nginx_conf_new,target=/etc/nginx/nginx.conf \
            --config-rm nginx_snippets_oauth2 \
            --config-add source=nginx_snippets_oauth2_new,target=/etc/nginx/snippets/oauth2_headers.conf \
            club_manager_dev_nginx
          docker config rm nginx_conf || true
          docker config rm nginx_snippets_oauth2 || true
          docker config create nginx_conf ./reverse-proxy/nginx.conf
          docker config create nginx_snippets_oauth2 ./reverse-proxy/snippets/oauth2_headers.conf
      
          docker service update \
            --config-rm nginx_conf_new \
            --config-add source=nginx_conf,target=/etc/nginx/nginx.conf \
            --config-rm nginx_snippets_oauth2_new \
            --config-add source=nginx_snippets_oauth2,target=/etc/nginx/snippets/oauth2_headers.conf \
            club_manager_dev_nginx
      
          docker config rm nginx_conf_new || true
          docker config rm nginx_snippets_oauth2_new || true