server {
    listen 80;
    server_name club-manager.local;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /idp/ {
        proxy_pass http://192.168.0.65:8180/;
    }
}